config/routes.rb
Rails.application.routes.draw do
  resources :players do
    member do
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "players#index"
  get "/new_it", to: "players#new_it"
  put "/new_it_put", to: "players#new_it_put"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
    enum send_email?: { yes: 1, no: 0 }, _prefix: :send_email, _default: :yes
    enum is_it: { yes: 1, no: 0 }, _prefix: :is_it, _default: :no
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
    @player = @players.is_it_yes.first
    
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_it_put
    @player = Player.find(params[:player])
    Player.update_all(is_it: :no)
    @player.update(is_it: :yes)
    PlayerMailer.with(player: @player).new_it.deliver_now
    redirect_to players_path
  end

  def new_it
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :email, :send_email?, :is_it)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="rtl" lang="he">
  <head>
    <title>Tag</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <main class="container" >
    <%= yield %>
  </main>
  </body>
</html>

app/views/players/_form.html.erb
<%= simple_form_for(@player) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input "send_email?" %>
    <%= f.input :is_it, collection: Player.is_its.map{ |i| [i[0], i[0]] } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= player.email %>
  </p>

  <p>
    <strong>Send email?:</strong>
    <%= player.send_email? %>
  </p>

</div>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<div class="d-flex flex-column justify-content-center vh100">
  <h1 class="text-center display-1 fw-bold">
    <%= @player&.name%>
  </h1>
  <h2 class="text-center mt-1 mb-5">
    תופס
  </h2>

  <%= link_to 'יש תופס חדש?', new_it_path, class: "text-center d-block my-5" %>
</div>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/new_it.html.erb
<%= form_with(url: new_it_put_path, local: false, method: :put, class: "d-flex flex-column justify-content-center vh100") do |form| %>
  <div class="form-group">
  <h1 >
    <%= form.label :player, "מי תופס?" %>
  </h1>
    <%= form.select :player, options_for_select(Player.all.map{ |player| [player.name, player.id] }), { include_blank: true }, class: "form-control my-3" %>
  </div>

  <%= form.submit "שליחה", class: "btn btn-primary" %>
<% end %>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Edit this player", edit_player_path(@player) %> |
  <%= link_to "Back to players", players_path %>

  <%= button_to "Destroy this player", @player, method: :delete %>
</div>